#!/bin/sh

# Stop the queue worker
php /var/www/on/builder-laravel/artisan queue:work --stop-when-empty

git --work-tree=/var/www/on/builder-laravel --git-dir=/var/repo/on/builder-laravel checkout -f
cd /var/www/on/builder-laravel

chown -R www-data:www-data .
chmod -R 775 storage bootstrap/cache

COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev
php artisan migrate --force
# Disabled this as its done on pre-commit
# npm i 
# npm run production

chown -R www-data:www-data .
chmod -R 775 storage bootstrap/cache


# Restart the queue worker (run this command in the background or as a separate process)
nohup php /var/www/on/builder-laravel/artisan queue:work > /dev/null 2>&1 &
